# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-customer-receiver-queries:
    build:
      target: development
    image: ffc-sfd-customer-receiver-queries-development
    container_name: ffc-sfd-customer-receiver-queries-development
    ports:
      - "3016:3016"
      - "9016:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json