- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: QUERIES_TOPIC_ADDRESS
  value: "fcp-sfd-customer-queries"
- key: QUERIES_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-customer-receiver-queries"